import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import me from "../public/me.png";
import Image from "next/image";
import td from "../public/threedots.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">welcome!</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-red-500 text- to-red-800 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1UmCprFmPi1eRS0YmOku7dHpbe_REBJqH/view?usp=drive_link" target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-red-700 font-medium dark:text-red-700 md:text-6xl">
              Can Gokmen
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              CS & Math Student @ Boston University
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Aspiring Software Engineer with an interest in AI, currently a freshman
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/cangokmen/" target="_blank"><AiFillLinkedin /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={me} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py- dark:text-white ">Courses</h3>
          </div>
          <div className="lg:flex gap-5">
            <div className="text-center shadow-lg p-6 rounded-xl my-10  dark:bg-white flex-1">
              <h4 className="py-4 text-red-700">CS210: Computer Systems</h4>
              <h4 className="py-4 text-red-700">MA225: Multivariate Calculus</h4>
              <h4 className="py-4 text-red-700">MA242: Linear Algebra</h4>
              <h4 className="py-4 text-red-700">WR120: First-Year Writing Seminar</h4>
              <h4 className="py-4 text-red-700">CS392 C1: Algorithms for Competitive Programming</h4>
              <h4 className="py-4 text-red-700">HI151: The Emerging United States to 1865</h4>
              <h4 className="py-4 text-red-700">CS112: Introduction to Computer Science 2</h4>
              <h4 className="py-4 text-red-700">CS131: Combinatoric Structures</h4>
              <h4 className="py-4 text-red-700">WR112: Academic Writing for ELL Students 2</h4>

            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Soon to be filled with interesting ideas...
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={td}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
